use_frameworks!

target 'LXDCategory_Example' do
  pod 'LXDCategory', :path => '../'
  pod 'LXDMacros', '~>0.1.4'

  target 'LXDCategory_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end


